### ISSUE TITLE
Harvest Pylon is losing data

### ISSUE THREAD

**Issue by Saereth** [jeremiahwinsley/pylons#28] opened 2024-08-23 18:19 UTC
Neoforge 21.2.22
mc 1.21.1
pylons-1.21.0-5.0.1

Harvester Pylon losing inventory and owner. Will not work after a logging in later. Looses the hoe I put in and its "owner".
Initial setup
![image](https://github.com/user-attachments/assets/ded37d82-b6ee-48ac-b02a-9095b283af7d)

and then later after logging for a bit/coming back...

![image](https://github.com/user-attachments/assets/7c768b98-6478-4097-8895-3c6a6dc5f85f)

**Comment by jeremiahwinsley** [comment] 2024-08-23 19:57
Tested both in my dev environment and on an ATM10 server, and I'm not able to replicate this with just pylons and mystical agriculture. Any relevant errors in the logs? This looks like there was an error saving the block to disk, which typically will show up there.

**Comment by Saereth** [comment] 2024-08-23 21:42
no I don't see any errors in the logs but I'll try with a smaller modest and see what I can figured out and get back to you

**Comment by HNGamingUK** [comment] 2024-08-24 19:19
I have found the same thing happening on ATM10 pack version 0.36 I did see it spam the server console when the hoe was put in initially but didn't note it down. I've spawned a new hoe in put it in the pylon. Will monitor to see if it does the same again...

**Comment by jeremiahwinsley** [comment] 2024-08-25 00:28
I managed to reproduce the issue, a spawned in supremium hoe does not crash, but if I craft a supremium hoe manually, it has invalid data and fails to save. I have reported this to MA here: https://github.com/BlakeBr0/MysticalAgriculture/issues/708

**Comment by Saereth** [comment] 2024-08-25 00:46
awesome troubleshooting on that, ty!

**Comment by HNGamingUK** [comment] 2024-08-25 06:24
Ah that makes sense why it didn't do it for the one I spawned in, hopefully will be fixed soon. In the meantime I will just make it and then spawn one in and delete the crafted one.

**Comment by jeremiahwinsley** [comment] 2024-08-26 18:00
Should be fixed in latest MA release.

**Closed by jeremiahwinsley** 2024-08-26 18:00 UTC
